### ISSUE TITLE
FEATURE: Support for adjusting private key length

### ISSUE THREAD

**Issue by areis422** [webprofusion/certify#466]
Please implement a way to change the size of the generated private key. Minimum length should default to 2048, but allow up to 16384, which is the max size allowed at this time by schannel.

**Comment by areis422** [comment]
Reference File: /src/Certify.Shared/Management/CertificateManager.cs

**Comment by webprofusion-chrisc** [comment]
Thanks, yes agreed!

I'm sure this issue might be a dupe but I'll leave it open anyway.

**Comment by areis422** [comment]
Bump, any update?

**Comment by webprofusion-chrisc** [comment]
Nothing yet, the key size is currently fixed in the Certes library, I just haven't gotten round to either removing that dependency or patching certes. Most work at the moment is on stabilizing the 5.x release of Certify but this will get done eventually.

**Comment by webprofusion-chrisc** [comment]
Note also that Let's Encrypt RSA key sizes are limited to 2048, 3072 or 4096 and EC keys are completely different (so this issue only relates to RSA keys). Other CAs (especially custom ones) will likely support higher key sizes but the limit will vary by CA (and we are now multi-CA aware).

**Comment by areis422** [comment]
Agreed. I'm more looking for RSA 4096 as a standard option at the moment. When it comes to EC certificates, I know there's pretty wide-spread support, but until IIS and Nginx can do dual certificates (apache currently can) I don't see a dire need for EC right this moment. Plus, you never know what Microsoft will do with SChannel from month to month. I mean we're into Server 2019 and still don't have proper TLS v1.3 support....

**Comment by webprofusion-chrisc** [comment]
Hi, this is fixed in Certify The Web 5.5.1 now, you currently need to specify it per managed certificate under Certificate > Advanced > Signing & Security. Support for different RSA key sizes varies by Certificate Authority.
